/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AppCabinetRouteImport } from './routes/_app/cabinet'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicRatingsRouteImport } from './routes/_public/ratings'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as ConsoleTournamentIdRouteImport } from './routes/console/$tournamentId'
import { Route as ScreenPublicTokenRouteImport } from './routes/screen.$publicToken'
import { Route as PublicPlayersPlayerIdRouteImport } from './routes/_public/players.$playerId'
import { Route as PublicTournamentsIndexRouteImport } from './routes/_public/tournaments.index'
import { Route as PublicTournamentsTournamentIdRouteImport } from './routes/_public/tournaments.$tournamentId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCabinetRoute = AppCabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => AppRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRatingsRoute = PublicRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => PublicRoute,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleTournamentIdRoute = ConsoleTournamentIdRouteImport.update({
  id: '/$tournamentId',
  path: '/$tournamentId',
  getParentRoute: () => ConsoleRoute,
} as any)
const ScreenPublicTokenRoute = ScreenPublicTokenRouteImport.update({
  id: '/screen/$publicToken',
  path: '/screen/$publicToken',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPlayersPlayerIdRoute = PublicPlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTournamentsIndexRoute = PublicTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTournamentsTournamentIdRoute =
  PublicTournamentsTournamentIdRouteImport.update({
    id: '/tournaments/$tournamentId',
    path: '/tournaments/$tournamentId',
    getParentRoute: () => PublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/cabinet': typeof AppCabinetRoute
  '/login': typeof PublicLoginRoute
  '/ratings': typeof PublicRatingsRoute
  '/console/$tournamentId': typeof ConsoleTournamentIdRoute
  '/screen/$publicToken': typeof ScreenPublicTokenRoute
  '/console/': typeof ConsoleIndexRoute
  '/players/$playerId': typeof PublicPlayersPlayerIdRoute
  '/tournaments/$tournamentId': typeof PublicTournamentsTournamentIdRoute
  '/tournaments/': typeof PublicTournamentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/cabinet': typeof AppCabinetRoute
  '/login': typeof PublicLoginRoute
  '/ratings': typeof PublicRatingsRoute
  '/console/$tournamentId': typeof ConsoleTournamentIdRoute
  '/screen/$publicToken': typeof ScreenPublicTokenRoute
  '/console': typeof ConsoleIndexRoute
  '/players/$playerId': typeof PublicPlayersPlayerIdRoute
  '/tournaments/$tournamentId': typeof PublicTournamentsTournamentIdRoute
  '/tournaments': typeof PublicTournamentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/console': typeof ConsoleRouteWithChildren
  '/_app/cabinet': typeof AppCabinetRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/ratings': typeof PublicRatingsRoute
  '/console/$tournamentId': typeof ConsoleTournamentIdRoute
  '/screen/$publicToken': typeof ScreenPublicTokenRoute
  '/_public/': typeof PublicIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/_public/players/$playerId': typeof PublicPlayersPlayerIdRoute
  '/_public/tournaments/$tournamentId': typeof PublicTournamentsTournamentIdRoute
  '/_public/tournaments/': typeof PublicTournamentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/cabinet'
    | '/login'
    | '/ratings'
    | '/console/$tournamentId'
    | '/screen/$publicToken'
    | '/console/'
    | '/players/$playerId'
    | '/tournaments/$tournamentId'
    | '/tournaments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cabinet'
    | '/login'
    | '/ratings'
    | '/console/$tournamentId'
    | '/screen/$publicToken'
    | '/console'
    | '/players/$playerId'
    | '/tournaments/$tournamentId'
    | '/tournaments'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/console'
    | '/_app/cabinet'
    | '/_public/login'
    | '/_public/ratings'
    | '/console/$tournamentId'
    | '/screen/$publicToken'
    | '/_public/'
    | '/console/'
    | '/_public/players/$playerId'
    | '/_public/tournaments/$tournamentId'
    | '/_public/tournaments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ConsoleRoute: typeof ConsoleRouteWithChildren
  ScreenPublicTokenRoute: typeof ScreenPublicTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/cabinet': {
      id: '/_app/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof AppCabinetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/ratings': {
      id: '/_public/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof PublicRatingsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/$tournamentId': {
      id: '/console/$tournamentId'
      path: '/$tournamentId'
      fullPath: '/console/$tournamentId'
      preLoaderRoute: typeof ConsoleTournamentIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/screen/$publicToken': {
      id: '/screen/$publicToken'
      path: '/screen/$publicToken'
      fullPath: '/screen/$publicToken'
      preLoaderRoute: typeof ScreenPublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/players/$playerId': {
      id: '/_public/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PublicPlayersPlayerIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/tournaments/': {
      id: '/_public/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof PublicTournamentsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/tournaments/$tournamentId': {
      id: '/_public/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof PublicTournamentsTournamentIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AppRouteChildren {
  AppCabinetRoute: typeof AppCabinetRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCabinetRoute: AppCabinetRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRatingsRoute: typeof PublicRatingsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicPlayersPlayerIdRoute: typeof PublicPlayersPlayerIdRoute
  PublicTournamentsTournamentIdRoute: typeof PublicTournamentsTournamentIdRoute
  PublicTournamentsIndexRoute: typeof PublicTournamentsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRatingsRoute: PublicRatingsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicPlayersPlayerIdRoute: PublicPlayersPlayerIdRoute,
  PublicTournamentsTournamentIdRoute: PublicTournamentsTournamentIdRoute,
  PublicTournamentsIndexRoute: PublicTournamentsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface ConsoleRouteChildren {
  ConsoleTournamentIdRoute: typeof ConsoleTournamentIdRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleTournamentIdRoute: ConsoleTournamentIdRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ConsoleRoute: ConsoleRouteWithChildren,
  ScreenPublicTokenRoute: ScreenPublicTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
